### ISSUE TITLE
[Bug] None of the components of site are working

### ISSUE THREAD

**Issue by aj11anuj** [ksctl/ksctl-website#1]
I just landed to this site in order to check it and I found that -
- None of the components are loading properly
- Buttons are not working
- Even the logo of ksctl not appearing
- Any redirect link provided is also not working

I'm not sure of the solution but I think there is some problem with that next.js application.  

I checked that `docs.ksctl.com` is working fine, there is some problem with `home.ksctl.com`
![Screenshot (961)](https://github.com/ksctl/ksctl-website/assets/116108975/7f00d3b8-a6d7-4aa5-bab5-8cbba6024cbe)

**Comment by dipankardas011** [comment]
@aj11anuj yes it was just to try it out
nothing else we will be soon make a website for ksctl.com replacing the existing one
